CREATE TABLE public.auth_group (
	id bigserial NOT NULL,
	"name" varchar(150) NOT NULL,
	CONSTRAINT auth_group_id_not_null NOT NULL id,
	CONSTRAINT auth_group_name_key UNIQUE (name),
	CONSTRAINT auth_group_name_not_null NOT NULL name,
	CONSTRAINT auth_group_pkey PRIMARY KEY (id)
);

CREATE TABLE public.django_content_type (
	id bigserial NOT NULL,
	app_label varchar(100) NOT NULL,
	model varchar(100) NOT NULL,
	CONSTRAINT django_content_type_app_label_model_key UNIQUE (app_label, model),
	CONSTRAINT django_content_type_app_label_not_null NOT NULL app_label,
	CONSTRAINT django_content_type_id_not_null NOT NULL id,
	CONSTRAINT django_content_type_model_not_null NOT NULL model,
	CONSTRAINT django_content_type_pkey PRIMARY KEY (id)
);

CREATE TABLE public.django_migrations (
	id bigserial NOT NULL,
	app varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	applied timestamp NOT NULL,
	CONSTRAINT django_migrations_app_not_null NOT NULL app,
	CONSTRAINT django_migrations_applied_not_null NOT NULL applied,
	CONSTRAINT django_migrations_id_not_null NOT NULL id,
	CONSTRAINT django_migrations_name_not_null NOT NULL name,
	CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);
CREATE INDEX django_migrations_app_idx ON public.django_migrations USING btree (app);

CREATE TABLE public.django_session (
	session_key varchar(40) NOT NULL,
	session_data text NOT NULL,
	expire_date timestamp NOT NULL,
	CONSTRAINT django_session_expire_date_not_null NOT NULL expire_date,
	CONSTRAINT django_session_pkey PRIMARY KEY (session_key),
	CONSTRAINT django_session_session_data_not_null NOT NULL session_data,
	CONSTRAINT django_session_session_key_not_null NOT NULL session_key
);
CREATE INDEX django_session_expire_date_idx ON public.django_session USING btree (expire_date);

CREATE TABLE public.auth_permission (
	id bigserial NOT NULL,
	"name" varchar(255) NOT NULL,
	content_type_id int8 NOT NULL,
	codename varchar(100) NOT NULL,
	CONSTRAINT auth_permission_codename_not_null NOT NULL codename,
	CONSTRAINT auth_permission_content_type_id_codename_key UNIQUE (content_type_id, codename),
	CONSTRAINT auth_permission_content_type_id_not_null NOT NULL content_type_id,
	CONSTRAINT auth_permission_id_not_null NOT NULL id,
	CONSTRAINT auth_permission_name_not_null NOT NULL name,
	CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
	CONSTRAINT auth_permission_content_type_id_fkey FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id)
);
CREATE INDEX auth_permission_content_type_id_idx ON public.auth_permission USING btree (content_type_id);

CREATE TABLE public.authentication_user (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"password" varchar(128) NOT NULL,
	last_login timestamptz NULL,
	is_superuser bool NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	phone_number varchar(10) NOT NULL,
	"name" varchar(255) NOT NULL,
	email varchar(254) NULL,
	totp_secret varchar(32) NULL,
	totp_enabled bool NOT NULL,
	totp_last_counter int8 NULL,
	failed_totp_attempts int4 NOT NULL DEFAULT 0,
	totp_lockout_until timestamptz NULL,
	is_verified bool NOT NULL,
	is_staff bool NOT NULL,
	is_active bool NOT NULL,
	date_joined timestamptz NOT NULL,
	created_by_id int8 NULL,
	verified_by_id int8 NULL,
	CONSTRAINT authentication_user_created_at_not_null NOT NULL created_at,
	CONSTRAINT authentication_user_date_joined_not_null NOT NULL date_joined,
	CONSTRAINT authentication_user_id_not_null NOT NULL id,
	CONSTRAINT authentication_user_is_active_not_null NOT NULL is_active,
	CONSTRAINT authentication_user_is_staff_not_null NOT NULL is_staff,
	CONSTRAINT authentication_user_is_superuser_not_null NOT NULL is_superuser,
	CONSTRAINT authentication_user_is_verified_not_null NOT NULL is_verified,
	CONSTRAINT authentication_user_name_not_null NOT NULL name,
	CONSTRAINT authentication_user_password_not_null NOT NULL password,
	CONSTRAINT authentication_user_phone_number_key UNIQUE (phone_number),
	CONSTRAINT authentication_user_phone_number_not_null NOT NULL phone_number,
	CONSTRAINT authentication_user_pkey PRIMARY KEY (id),
	CONSTRAINT authentication_user_totp_enabled_not_null NOT NULL totp_enabled,
	CONSTRAINT authentication_user_failed_totp_attempts_not_null NOT NULL failed_totp_attempts,
	CONSTRAINT authentication_user_updated_at_not_null NOT NULL updated_at,
	CONSTRAINT authentication_user_created_by_id_d3f2a616_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT authentication_user_verified_by_id_e9e11f40_fk_authentic FOREIGN KEY (verified_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX authentication_user_created_by_id_d3f2a616 ON public.authentication_user USING btree (created_by_id);
CREATE INDEX authentication_user_phone_number_f8159965_like ON public.authentication_user USING btree (phone_number varchar_pattern_ops);
CREATE INDEX authentication_user_verified_by_id_e9e11f40 ON public.authentication_user USING btree (verified_by_id);

CREATE TABLE public.authentication_user_groups (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NOT NULL,
	group_id int4 NOT NULL,
	CONSTRAINT authentication_user_groups_group_id_not_null NOT NULL group_id,
	CONSTRAINT authentication_user_groups_id_not_null NOT NULL id,
	CONSTRAINT authentication_user_groups_pkey PRIMARY KEY (id),
	CONSTRAINT authentication_user_groups_user_id_group_id_8af031ac_uniq UNIQUE (user_id, group_id),
	CONSTRAINT authentication_user_groups_user_id_not_null NOT NULL user_id,
	CONSTRAINT authentication_user__user_id_30868577_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT authentication_user_groups_group_id_6b5c44b7_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX authentication_user_groups_group_id_6b5c44b7 ON public.authentication_user_groups USING btree (group_id);
CREATE INDEX authentication_user_groups_user_id_30868577 ON public.authentication_user_groups USING btree (user_id);

CREATE TABLE public.authentication_user_user_permissions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NOT NULL,
	permission_id int4 NOT NULL,
	CONSTRAINT authentication_user_user_permissions_id_not_null NOT NULL id,
	CONSTRAINT authentication_user_user_permissions_permission_id_not_null NOT NULL permission_id,
	CONSTRAINT authentication_user_user_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT authentication_user_user_permissions_user_id_not_null NOT NULL user_id,
	CONSTRAINT authentication_user_user_user_id_permission_id_ec51b09f_uniq UNIQUE (user_id, permission_id),
	CONSTRAINT authentication_user__permission_id_ea6be19a_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT authentication_user__user_id_736ebf7e_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX authentication_user_user_permissions_permission_id_ea6be19a ON public.authentication_user_user_permissions USING btree (permission_id);
CREATE INDEX authentication_user_user_permissions_user_id_736ebf7e ON public.authentication_user_user_permissions USING btree (user_id);


CREATE TABLE public.django_admin_log (
	id bigserial NOT NULL,
	action_time timestamp NOT NULL,
	user_id int8 NULL,
	content_type_id int8 NULL,
	object_id text NULL,
	object_repr varchar(200) NOT NULL,
	action_flag int2 NOT NULL,
	change_message text NOT NULL,
	CONSTRAINT django_admin_log_action_flag_not_null NOT NULL action_flag,
	CONSTRAINT django_admin_log_action_time_not_null NOT NULL action_time,
	CONSTRAINT django_admin_log_change_message_not_null NOT NULL change_message,
	CONSTRAINT django_admin_log_id_not_null NOT NULL id,
	CONSTRAINT django_admin_log_object_repr_not_null NOT NULL object_repr,
	CONSTRAINT django_admin_log_pkey PRIMARY KEY (id),
	CONSTRAINT django_admin_log_content_type_id_fkey FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id),
	CONSTRAINT django_admin_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL
);
CREATE INDEX django_admin_log_content_type_id_idx ON public.django_admin_log USING btree (content_type_id);
CREATE INDEX django_admin_log_user_id_idx ON public.django_admin_log USING btree (user_id);


CREATE TABLE public.auth_group_permissions (
	id bigserial NOT NULL,
	group_id int8 NOT NULL,
	permission_id int8 NOT NULL,
	CONSTRAINT auth_group_permissions_group_id_not_null NOT NULL group_id,
	CONSTRAINT auth_group_permissions_group_id_permission_id_key UNIQUE (group_id, permission_id),
	CONSTRAINT auth_group_permissions_id_not_null NOT NULL id,
	CONSTRAINT auth_group_permissions_permission_id_not_null NOT NULL permission_id,
	CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT auth_group_permissions_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.auth_group(id) ON DELETE CASCADE,
	CONSTRAINT auth_group_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) ON DELETE CASCADE
);
CREATE INDEX auth_group_permissions_group_id_idx ON public.auth_group_permissions USING btree (group_id);
CREATE INDEX auth_group_permissions_permission_id_idx ON public.auth_group_permissions USING btree (permission_id);

CREATE TABLE public.authentication_admin (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL,
	deleted_at timestamptz NULL,
	deleted_by_id int8 NULL,
	created_by_id int8 NULL,
	user_id int8 NOT NULL,
	CONSTRAINT authentication_admin_created_at_not_null NOT NULL created_at,
	CONSTRAINT authentication_admin_id_not_null NOT NULL id,
	CONSTRAINT authentication_admin_is_deleted_not_null NOT NULL is_deleted,
	CONSTRAINT authentication_admin_pkey PRIMARY KEY (id),
	CONSTRAINT authentication_admin_updated_at_not_null NOT NULL updated_at,
	CONSTRAINT authentication_admin_user_id_key UNIQUE (user_id),
	CONSTRAINT authentication_admin_user_id_not_null NOT NULL user_id,
	CONSTRAINT authentication_admin_created_by_id_16c58a5c_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT authentication_admin_deleted_by_id_ba1bf8d2_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT authentication_admin_user_id_2e7e3e20_fk_authentication_user_id FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX authentication_admin_created_by_id_16c58a5c ON public.authentication_admin USING btree (created_by_id);
CREATE INDEX authentication_admin_deleted_by_id_ba1bf8d2 ON public.authentication_admin USING btree (deleted_by_id);
CREATE INDEX authentication_admin_is_deleted_699f106c ON public.authentication_admin USING btree (is_deleted);

CREATE TABLE public.authentication_salesperson (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL,
	deleted_at timestamptz NULL,
	deleted_by_id int8 NULL,
	created_by_id int8 NULL,
	user_id int8 NOT NULL,
	CONSTRAINT authentication_salesperson_created_at_not_null NOT NULL created_at,
	CONSTRAINT authentication_salesperson_id_not_null NOT NULL id,
	CONSTRAINT authentication_salesperson_is_deleted_not_null NOT NULL is_deleted,
	CONSTRAINT authentication_salesperson_pkey PRIMARY KEY (id),
	CONSTRAINT authentication_salesperson_updated_at_not_null NOT NULL updated_at,
	CONSTRAINT authentication_salesperson_user_id_key UNIQUE (user_id),
	CONSTRAINT authentication_salesperson_user_id_not_null NOT NULL user_id,
	CONSTRAINT authentication_sales_created_by_id_a1b95e80_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT authentication_sales_deleted_by_id_a5490b20_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT authentication_sales_user_id_23cc5271_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX authentication_salesperson_created_by_id_a1b95e80 ON public.authentication_salesperson USING btree (created_by_id);
CREATE INDEX authentication_salesperson_deleted_by_id_a5490b20 ON public.authentication_salesperson USING btree (deleted_by_id);
CREATE INDEX authentication_salesperson_is_deleted_e9d86904 ON public.authentication_salesperson USING btree (is_deleted);

CREATE TABLE public.authtoken_token (
	"key" varchar(40) NOT NULL,
	created timestamptz NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT authtoken_token_created_not_null NOT NULL created,
	CONSTRAINT authtoken_token_key_not_null NOT NULL key,
	CONSTRAINT authtoken_token_pkey PRIMARY KEY (key),
	CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id),
	CONSTRAINT authtoken_token_user_id_not_null NOT NULL user_id
);
CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);

CREATE TABLE public.aggregator_address (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL,
	deleted_at timestamptz NULL,
	address_line_1 varchar(255) NOT NULL,
	address_line_2 varchar(255) NOT NULL,
	created_by_id int8 NULL,
	deleted_by_id int8 NULL,
	city_id int8 NOT NULL,
	country_id int8 NOT NULL,
	pincode_id int8 NOT NULL,
	state_id int8 NOT NULL,
	CONSTRAINT aggregator_address_address_line_1_not_null NOT NULL address_line_1,
	CONSTRAINT aggregator_address_address_line_2_not_null NOT NULL address_line_2,
	CONSTRAINT aggregator_address_city_id_not_null NOT NULL city_id,
	CONSTRAINT aggregator_address_country_id_not_null NOT NULL country_id,
	CONSTRAINT aggregator_address_created_at_not_null NOT NULL created_at,
	CONSTRAINT aggregator_address_id_not_null NOT NULL id,
	CONSTRAINT aggregator_address_is_deleted_not_null NOT NULL is_deleted,
	CONSTRAINT aggregator_address_pincode_id_not_null NOT NULL pincode_id,
	CONSTRAINT aggregator_address_pkey PRIMARY KEY (id),
	CONSTRAINT aggregator_address_state_id_not_null NOT NULL state_id,
	CONSTRAINT aggregator_address_updated_at_not_null NOT NULL updated_at
);
CREATE INDEX aggregator_address_city_id_96970770 ON public.aggregator_address USING btree (city_id);
CREATE INDEX aggregator_address_country_id_2f36b787 ON public.aggregator_address USING btree (country_id);
CREATE INDEX aggregator_address_created_by_id_58fd480f ON public.aggregator_address USING btree (created_by_id);
CREATE INDEX aggregator_address_deleted_by_id_dc377b3e ON public.aggregator_address USING btree (deleted_by_id);
CREATE INDEX aggregator_address_is_deleted_4785bd2d ON public.aggregator_address USING btree (is_deleted);
CREATE INDEX aggregator_address_pincode_id_08ed1fa7 ON public.aggregator_address USING btree (pincode_id);
CREATE INDEX aggregator_address_state_id_f6223e91 ON public.aggregator_address USING btree (state_id);

CREATE TABLE public.aggregator_city (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL,
	deleted_at timestamptz NULL,
	"name" varchar(255) NOT NULL,
	created_by_id int8 NULL,
	deleted_by_id int8 NULL,
	state_id int8 NOT NULL,
	CONSTRAINT aggregator_city_created_at_not_null NOT NULL created_at,
	CONSTRAINT aggregator_city_id_not_null NOT NULL id,
	CONSTRAINT aggregator_city_is_deleted_not_null NOT NULL is_deleted,
	CONSTRAINT aggregator_city_name_not_null NOT NULL name,
	CONSTRAINT aggregator_city_pkey PRIMARY KEY (id),
	CONSTRAINT aggregator_city_state_id_not_null NOT NULL state_id,
	CONSTRAINT aggregator_city_updated_at_not_null NOT NULL updated_at,
	CONSTRAINT uniq_city_state_name UNIQUE (state_id, name)
);
CREATE INDEX aggregator_city_created_by_id_fefe63ee ON public.aggregator_city USING btree (created_by_id);
CREATE INDEX aggregator_city_deleted_by_id_73898851 ON public.aggregator_city USING btree (deleted_by_id);
CREATE INDEX aggregator_city_is_deleted_5d1d102e ON public.aggregator_city USING btree (is_deleted);
CREATE INDEX aggregator_city_state_id_cf1a9769 ON public.aggregator_city USING btree (state_id);

CREATE TABLE public.aggregator_country (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL,
	deleted_at timestamptz NULL,
	"name" varchar(255) NOT NULL,
	iso_code varchar(3) NOT NULL,
	created_by_id int8 NULL,
	deleted_by_id int8 NULL,
	CONSTRAINT aggregator_country_created_at_not_null NOT NULL created_at,
	CONSTRAINT aggregator_country_id_not_null NOT NULL id,
	CONSTRAINT aggregator_country_is_deleted_not_null NOT NULL is_deleted,
	CONSTRAINT aggregator_country_iso_code_key UNIQUE (iso_code),
	CONSTRAINT aggregator_country_iso_code_not_null NOT NULL iso_code,
	CONSTRAINT aggregator_country_name_key UNIQUE (name),
	CONSTRAINT aggregator_country_name_not_null NOT NULL name,
	CONSTRAINT aggregator_country_pkey PRIMARY KEY (id),
	CONSTRAINT aggregator_country_updated_at_not_null NOT NULL updated_at
);
CREATE INDEX aggregator_country_created_by_id_793f2516 ON public.aggregator_country USING btree (created_by_id);
CREATE INDEX aggregator_country_deleted_by_id_92252d30 ON public.aggregator_country USING btree (deleted_by_id);
CREATE INDEX aggregator_country_is_deleted_c078494b ON public.aggregator_country USING btree (is_deleted);
CREATE INDEX aggregator_country_iso_code_65034c84_like ON public.aggregator_country USING btree (iso_code varchar_pattern_ops);
CREATE INDEX aggregator_country_name_74cb7636_like ON public.aggregator_country USING btree (name varchar_pattern_ops);

CREATE TABLE public.aggregator_pincode (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL,
	deleted_at timestamptz NULL,
	code varchar(10) NOT NULL,
	city_id int8 NOT NULL,
	created_by_id int8 NULL,
	deleted_by_id int8 NULL,
	CONSTRAINT aggregator_pincode_city_id_not_null NOT NULL city_id,
	CONSTRAINT aggregator_pincode_code_not_null NOT NULL code,
	CONSTRAINT aggregator_pincode_created_at_not_null NOT NULL created_at,
	CONSTRAINT aggregator_pincode_id_not_null NOT NULL id,
	CONSTRAINT aggregator_pincode_is_deleted_not_null NOT NULL is_deleted,
	CONSTRAINT aggregator_pincode_pkey PRIMARY KEY (id),
	CONSTRAINT aggregator_pincode_updated_at_not_null NOT NULL updated_at,
	CONSTRAINT uniq_pincode_city_code UNIQUE (city_id, code)
);
CREATE INDEX aggregator_pincode_city_id_22cea78d ON public.aggregator_pincode USING btree (city_id);
CREATE INDEX aggregator_pincode_code_811fb568 ON public.aggregator_pincode USING btree (code);
CREATE INDEX aggregator_pincode_code_811fb568_like ON public.aggregator_pincode USING btree (code varchar_pattern_ops);
CREATE INDEX aggregator_pincode_created_by_id_27d8c46d ON public.aggregator_pincode USING btree (created_by_id);
CREATE INDEX aggregator_pincode_deleted_by_id_ce50a668 ON public.aggregator_pincode USING btree (deleted_by_id);
CREATE INDEX aggregator_pincode_is_deleted_a155fcbe ON public.aggregator_pincode USING btree (is_deleted);

CREATE TABLE public.aggregator_state (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL,
	deleted_at timestamptz NULL,
	"name" varchar(255) NOT NULL,
	code varchar(10) NULL,
	country_id int8 NOT NULL,
	created_by_id int8 NULL,
	deleted_by_id int8 NULL,
	CONSTRAINT aggregator_state_country_id_not_null NOT NULL country_id,
	CONSTRAINT aggregator_state_created_at_not_null NOT NULL created_at,
	CONSTRAINT aggregator_state_id_not_null NOT NULL id,
	CONSTRAINT aggregator_state_is_deleted_not_null NOT NULL is_deleted,
	CONSTRAINT aggregator_state_name_not_null NOT NULL name,
	CONSTRAINT aggregator_state_pkey PRIMARY KEY (id),
	CONSTRAINT aggregator_state_updated_at_not_null NOT NULL updated_at,
	CONSTRAINT uniq_state_country_name UNIQUE (country_id, name)
);
CREATE INDEX aggregator_state_country_id_85c7cf77 ON public.aggregator_state USING btree (country_id);
CREATE INDEX aggregator_state_created_by_id_dfbd65c0 ON public.aggregator_state USING btree (created_by_id);
CREATE INDEX aggregator_state_deleted_by_id_13e63a1b ON public.aggregator_state USING btree (deleted_by_id);
CREATE INDEX aggregator_state_is_deleted_e8f057d4 ON public.aggregator_state USING btree (is_deleted);
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_city_id_96970770_fk_aggregator_city_id FOREIGN KEY (city_id) REFERENCES public.aggregator_city(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_country_id_2f36b787_fk_aggregator_country_id FOREIGN KEY (country_id) REFERENCES public.aggregator_country(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_created_by_id_58fd480f_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_deleted_by_id_dc377b3e_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_pincode_id_08ed1fa7_fk_aggregator_pincode_id FOREIGN KEY (pincode_id) REFERENCES public.aggregator_pincode(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_state_id_f6223e91_fk_aggregator_state_id FOREIGN KEY (state_id) REFERENCES public.aggregator_state(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_city ADD CONSTRAINT aggregator_city_created_by_id_fefe63ee_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_city ADD CONSTRAINT aggregator_city_deleted_by_id_73898851_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_city ADD CONSTRAINT aggregator_city_state_id_cf1a9769_fk_aggregator_state_id FOREIGN KEY (state_id) REFERENCES public.aggregator_state(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_country ADD CONSTRAINT aggregator_country_created_by_id_793f2516_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_country ADD CONSTRAINT aggregator_country_deleted_by_id_92252d30_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_pincode ADD CONSTRAINT aggregator_pincode_city_id_22cea78d_fk_aggregator_city_id FOREIGN KEY (city_id) REFERENCES public.aggregator_city(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_pincode ADD CONSTRAINT aggregator_pincode_created_by_id_27d8c46d_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_pincode ADD CONSTRAINT aggregator_pincode_deleted_by_id_ce50a668_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_state ADD CONSTRAINT aggregator_state_country_id_85c7cf77_fk_aggregator_country_id FOREIGN KEY (country_id) REFERENCES public.aggregator_country(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_state ADD CONSTRAINT aggregator_state_created_by_id_dfbd65c0_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_state ADD CONSTRAINT aggregator_state_deleted_by_id_13e63a1b_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;

-- ---------------------------------------------------------------------------
-- Referential actions (ON DELETE) aligned with the Django models' on_delete.
-- Postgres cannot alter a constraint's action, so each FK is dropped and
-- re-created with the matching clause. PROTECT is written as RESTRICT
-- (Postgres rejects the PROTECT keyword; they are synonyms).
-- ---------------------------------------------------------------------------

-- Django Permission: content_type -> CASCADE
ALTER TABLE public.auth_permission DROP CONSTRAINT auth_permission_content_type_id_fkey;
ALTER TABLE public.auth_permission ADD CONSTRAINT auth_permission_content_type_id_fkey FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

-- Django LogEntry: user -> CASCADE, content_type -> SET NULL
ALTER TABLE public.django_admin_log DROP CONSTRAINT django_admin_log_user_id_fkey;
ALTER TABLE public.django_admin_log ADD CONSTRAINT django_admin_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.django_admin_log DROP CONSTRAINT django_admin_log_content_type_id_fkey;
ALTER TABLE public.django_admin_log ADD CONSTRAINT django_admin_log_content_type_id_fkey FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

-- authentication_user.created_by / verified_by -> RESTRICT (PROTECT): a user
-- who created/verified others can never be deleted while referenced.
ALTER TABLE public.authentication_user DROP CONSTRAINT authentication_user_created_by_id_d3f2a616_fk_authentic;
ALTER TABLE public.authentication_user ADD CONSTRAINT authentication_user_created_by_id_d3f2a616_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.authentication_user DROP CONSTRAINT authentication_user_verified_by_id_e9e11f40_fk_authentic;
ALTER TABLE public.authentication_user ADD CONSTRAINT authentication_user_verified_by_id_e9e11f40_fk_authentic FOREIGN KEY (verified_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

-- Django M2M through tables: -> CASCADE both directions
ALTER TABLE public.authentication_user_groups DROP CONSTRAINT authentication_user__user_id_30868577_fk_authentic;
ALTER TABLE public.authentication_user_groups ADD CONSTRAINT authentication_user__user_id_30868577_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.authentication_user_groups DROP CONSTRAINT authentication_user_groups_group_id_6b5c44b7_fk_auth_group_id;
ALTER TABLE public.authentication_user_groups ADD CONSTRAINT authentication_user_groups_group_id_6b5c44b7_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.authentication_user_user_permissions DROP CONSTRAINT authentication_user__permission_id_ea6be19a_fk_auth_perm;
ALTER TABLE public.authentication_user_user_permissions ADD CONSTRAINT authentication_user__permission_id_ea6be19a_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.authentication_user_user_permissions DROP CONSTRAINT authentication_user__user_id_736ebf7e_fk_authentic;
ALTER TABLE public.authentication_user_user_permissions ADD CONSTRAINT authentication_user__user_id_736ebf7e_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

-- authentication_admin: user CASCADE, created_by RESTRICT, deleted_by SET NULL
ALTER TABLE public.authentication_admin DROP CONSTRAINT authentication_admin_user_id_2e7e3e20_fk_authentication_user_id;
ALTER TABLE public.authentication_admin ADD CONSTRAINT authentication_admin_user_id_2e7e3e20_fk_authentication_user_id FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.authentication_admin DROP CONSTRAINT authentication_admin_created_by_id_16c58a5c_fk_authentic;
ALTER TABLE public.authentication_admin ADD CONSTRAINT authentication_admin_created_by_id_16c58a5c_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.authentication_admin DROP CONSTRAINT authentication_admin_deleted_by_id_ba1bf8d2_fk_authentic;
ALTER TABLE public.authentication_admin ADD CONSTRAINT authentication_admin_deleted_by_id_ba1bf8d2_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

-- authentication_salesperson: user CASCADE, created_by RESTRICT, deleted_by SET NULL
ALTER TABLE public.authentication_salesperson DROP CONSTRAINT authentication_sales_user_id_23cc5271_fk_authentic;
ALTER TABLE public.authentication_salesperson ADD CONSTRAINT authentication_sales_user_id_23cc5271_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.authentication_salesperson DROP CONSTRAINT authentication_sales_created_by_id_a1b95e80_fk_authentic;
ALTER TABLE public.authentication_salesperson ADD CONSTRAINT authentication_sales_created_by_id_a1b95e80_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.authentication_salesperson DROP CONSTRAINT authentication_sales_deleted_by_id_a5490b20_fk_authentic;
ALTER TABLE public.authentication_salesperson ADD CONSTRAINT authentication_sales_deleted_by_id_a5490b20_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

-- aggregator geography hierarchy: RESTRICT
ALTER TABLE public.aggregator_state DROP CONSTRAINT aggregator_state_country_id_85c7cf77_fk_aggregator_country_id;
ALTER TABLE public.aggregator_state ADD CONSTRAINT aggregator_state_country_id_85c7cf77_fk_aggregator_country_id FOREIGN KEY (country_id) REFERENCES public.aggregator_country(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_city DROP CONSTRAINT aggregator_city_state_id_cf1a9769_fk_aggregator_state_id;
ALTER TABLE public.aggregator_city ADD CONSTRAINT aggregator_city_state_id_cf1a9769_fk_aggregator_state_id FOREIGN KEY (state_id) REFERENCES public.aggregator_state(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_pincode DROP CONSTRAINT aggregator_pincode_city_id_22cea78d_fk_aggregator_city_id;
ALTER TABLE public.aggregator_pincode ADD CONSTRAINT aggregator_pincode_city_id_22cea78d_fk_aggregator_city_id FOREIGN KEY (city_id) REFERENCES public.aggregator_city(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address DROP CONSTRAINT aggregator_address_pincode_id_08ed1fa7_fk_aggregator_pincode_id;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_pincode_id_08ed1fa7_fk_aggregator_pincode_id FOREIGN KEY (pincode_id) REFERENCES public.aggregator_pincode(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address DROP CONSTRAINT aggregator_address_city_id_96970770_fk_aggregator_city_id;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_city_id_96970770_fk_aggregator_city_id FOREIGN KEY (city_id) REFERENCES public.aggregator_city(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address DROP CONSTRAINT aggregator_address_state_id_f6223e91_fk_aggregator_state_id;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_state_id_f6223e91_fk_aggregator_state_id FOREIGN KEY (state_id) REFERENCES public.aggregator_state(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address DROP CONSTRAINT aggregator_address_country_id_2f36b787_fk_aggregator_country_id;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_country_id_2f36b787_fk_aggregator_country_id FOREIGN KEY (country_id) REFERENCES public.aggregator_country(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

-- aggregator audit columns: created_by RESTRICT, deleted_by SET NULL
ALTER TABLE public.aggregator_country DROP CONSTRAINT aggregator_country_created_by_id_793f2516_fk_authentic;
ALTER TABLE public.aggregator_country ADD CONSTRAINT aggregator_country_created_by_id_793f2516_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_country DROP CONSTRAINT aggregator_country_deleted_by_id_92252d30_fk_authentic;
ALTER TABLE public.aggregator_country ADD CONSTRAINT aggregator_country_deleted_by_id_92252d30_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_state DROP CONSTRAINT aggregator_state_created_by_id_dfbd65c0_fk_authentic;
ALTER TABLE public.aggregator_state ADD CONSTRAINT aggregator_state_created_by_id_dfbd65c0_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_state DROP CONSTRAINT aggregator_state_deleted_by_id_13e63a1b_fk_authentic;
ALTER TABLE public.aggregator_state ADD CONSTRAINT aggregator_state_deleted_by_id_13e63a1b_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_city DROP CONSTRAINT aggregator_city_created_by_id_fefe63ee_fk_authentic;
ALTER TABLE public.aggregator_city ADD CONSTRAINT aggregator_city_created_by_id_fefe63ee_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_city DROP CONSTRAINT aggregator_city_deleted_by_id_73898851_fk_authentic;
ALTER TABLE public.aggregator_city ADD CONSTRAINT aggregator_city_deleted_by_id_73898851_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_pincode DROP CONSTRAINT aggregator_pincode_created_by_id_27d8c46d_fk_authentic;
ALTER TABLE public.aggregator_pincode ADD CONSTRAINT aggregator_pincode_created_by_id_27d8c46d_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_pincode DROP CONSTRAINT aggregator_pincode_deleted_by_id_ce50a668_fk_authentic;
ALTER TABLE public.aggregator_pincode ADD CONSTRAINT aggregator_pincode_deleted_by_id_ce50a668_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address DROP CONSTRAINT aggregator_address_created_by_id_58fd480f_fk_authentic;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_created_by_id_58fd480f_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address DROP CONSTRAINT aggregator_address_deleted_by_id_dc377b3e_fk_authentic;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_deleted_by_id_dc377b3e_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.authtoken_token ADD CONSTRAINT authtoken_token_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE authentication_salesperson
    ADD COLUMN city_id BIGINT NOT NULL,
    ADD CONSTRAINT fk_salesperson_city
        FOREIGN KEY (city_id)
        REFERENCES aggregator_city (id)
        ON DELETE RESTRICT;

CREATE INDEX authentication_salesperson_city_id
    ON authentication_salesperson (city_id);


ALTER TABLE authentication_admin
    ADD COLUMN can_update_stock_count boolean NOT NULL DEFAULT false;



-- =============================================================================
-- Sales domain: clients, catalogue, dispatch and orders (aggregator app)
-- Added tables. Reference tables first, then dependents.
-- All FKs DEFERRABLE INITIALLY DEFERRED to match the rest of the schema.
--   created_by_id -> ON DELETE RESTRICT (model PROTECT)
--   deleted_by_id -> ON DELETE SET NULL (model SET_NULL)
--   business FKs  -> ON DELETE RESTRICT (model PROTECT)
-- =============================================================================

-- aggregator_status ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.aggregator_status (
	id bigserial NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL DEFAULT false,
	deleted_at timestamptz NULL,
	deleted_by_id int8 NULL,
	created_by_id int8 NULL,
	code varchar(32) NOT NULL,
	"name" varchar(64) NOT NULL,
	sequence int2 NOT NULL DEFAULT 0,
	CONSTRAINT aggregator_status_pkey PRIMARY KEY (id),
	CONSTRAINT aggregator_status_code_key UNIQUE (code),
	CONSTRAINT aggregator_status_sequence_check CHECK (sequence >= 0)
);
CREATE INDEX IF NOT EXISTS aggregator_status_code_like ON public.aggregator_status USING btree (code varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS aggregator_status_is_deleted_idx ON public.aggregator_status USING btree (is_deleted);
CREATE INDEX IF NOT EXISTS aggregator_status_created_by_id_idx ON public.aggregator_status USING btree (created_by_id);
CREATE INDEX IF NOT EXISTS aggregator_status_deleted_by_id_idx ON public.aggregator_status USING btree (deleted_by_id);

-- aggregator_transportagency --------------------------------------------------
CREATE TABLE IF NOT EXISTS public.aggregator_transportagency (
	id bigserial NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL DEFAULT false,
	deleted_at timestamptz NULL,
	deleted_by_id int8 NULL,
	created_by_id int8 NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT aggregator_transportagency_pkey PRIMARY KEY (id),
	CONSTRAINT uniq_transportagency_name UNIQUE (name)
);
CREATE INDEX IF NOT EXISTS aggregator_transportagency_is_deleted_idx ON public.aggregator_transportagency USING btree (is_deleted);
CREATE INDEX IF NOT EXISTS aggregator_transportagency_created_by_id_idx ON public.aggregator_transportagency USING btree (created_by_id);
CREATE INDEX IF NOT EXISTS aggregator_transportagency_deleted_by_id_idx ON public.aggregator_transportagency USING btree (deleted_by_id);

-- aggregator_contact ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.aggregator_contact (
	id bigserial NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL DEFAULT false,
	deleted_at timestamptz NULL,
	deleted_by_id int8 NULL,
	created_by_id int8 NULL,
	"name" varchar(255) NOT NULL,
	phone_number varchar(10) NOT NULL,
	CONSTRAINT aggregator_contact_pkey PRIMARY KEY (id),
	CONSTRAINT uniq_contact_name_phone UNIQUE (name, phone_number)
);
CREATE INDEX IF NOT EXISTS aggregator_contact_is_deleted_idx ON public.aggregator_contact USING btree (is_deleted);
CREATE INDEX IF NOT EXISTS aggregator_contact_created_by_id_idx ON public.aggregator_contact USING btree (created_by_id);
CREATE INDEX IF NOT EXISTS aggregator_contact_deleted_by_id_idx ON public.aggregator_contact USING btree (deleted_by_id);

-- aggregator_client -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.aggregator_client (
	id bigserial NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL DEFAULT false,
	deleted_at timestamptz NULL,
	deleted_by_id int8 NULL,
	created_by_id int8 NULL,
	company_name varchar(255) NOT NULL,
	company_phone varchar(10) NOT NULL,
	gst_number varchar(15) NOT NULL,
	status_id int8 NOT NULL,
	verified_by_id int8 NULL,
	verified_at timestamptz NULL,
	CONSTRAINT aggregator_client_pkey PRIMARY KEY (id),
	CONSTRAINT aggregator_client_gst_number_key UNIQUE (gst_number)
);
CREATE INDEX IF NOT EXISTS aggregator_client_gst_number_like ON public.aggregator_client USING btree (gst_number varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS aggregator_client_status_id_idx ON public.aggregator_client USING btree (status_id);
CREATE INDEX IF NOT EXISTS aggregator_client_verified_by_id_idx ON public.aggregator_client USING btree (verified_by_id);
CREATE INDEX IF NOT EXISTS aggregator_client_is_deleted_idx ON public.aggregator_client USING btree (is_deleted);
CREATE INDEX IF NOT EXISTS aggregator_client_created_by_id_idx ON public.aggregator_client USING btree (created_by_id);
CREATE INDEX IF NOT EXISTS aggregator_client_deleted_by_id_idx ON public.aggregator_client USING btree (deleted_by_id);

-- aggregator_clientaddress ----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.aggregator_clientaddress (
	id bigserial NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL DEFAULT false,
	deleted_at timestamptz NULL,
	deleted_by_id int8 NULL,
	created_by_id int8 NULL,
	client_id int8 NOT NULL,
	address_id int8 NOT NULL,
	label varchar(64) NOT NULL,
	is_primary bool NOT NULL DEFAULT false,
	CONSTRAINT aggregator_clientaddress_pkey PRIMARY KEY (id),
	CONSTRAINT uniq_clientaddress_client_address UNIQUE (client_id, address_id)
);
CREATE INDEX IF NOT EXISTS aggregator_clientaddress_client_id_idx ON public.aggregator_clientaddress USING btree (client_id);
CREATE INDEX IF NOT EXISTS aggregator_clientaddress_address_id_idx ON public.aggregator_clientaddress USING btree (address_id);
CREATE INDEX IF NOT EXISTS aggregator_clientaddress_is_deleted_idx ON public.aggregator_clientaddress USING btree (is_deleted);
CREATE INDEX IF NOT EXISTS aggregator_clientaddress_created_by_id_idx ON public.aggregator_clientaddress USING btree (created_by_id);
CREATE INDEX IF NOT EXISTS aggregator_clientaddress_deleted_by_id_idx ON public.aggregator_clientaddress USING btree (deleted_by_id);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_clientaddress_one_primary ON public.aggregator_clientaddress USING btree (client_id) WHERE (is_primary AND NOT is_deleted);

-- aggregator_clientcontact ----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.aggregator_clientcontact (
	id bigserial NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL DEFAULT false,
	deleted_at timestamptz NULL,
	deleted_by_id int8 NULL,
	created_by_id int8 NULL,
	client_id int8 NOT NULL,
	contact_id int8 NOT NULL,
	"role" varchar(64) NOT NULL,
	is_primary bool NOT NULL DEFAULT false,
	CONSTRAINT aggregator_clientcontact_pkey PRIMARY KEY (id),
	CONSTRAINT uniq_clientcontact_client_contact UNIQUE (client_id, contact_id)
);
CREATE INDEX IF NOT EXISTS aggregator_clientcontact_client_id_idx ON public.aggregator_clientcontact USING btree (client_id);
CREATE INDEX IF NOT EXISTS aggregator_clientcontact_contact_id_idx ON public.aggregator_clientcontact USING btree (contact_id);
CREATE INDEX IF NOT EXISTS aggregator_clientcontact_is_deleted_idx ON public.aggregator_clientcontact USING btree (is_deleted);
CREATE INDEX IF NOT EXISTS aggregator_clientcontact_created_by_id_idx ON public.aggregator_clientcontact USING btree (created_by_id);
CREATE INDEX IF NOT EXISTS aggregator_clientcontact_deleted_by_id_idx ON public.aggregator_clientcontact USING btree (deleted_by_id);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_clientcontact_one_primary ON public.aggregator_clientcontact USING btree (client_id) WHERE (is_primary AND NOT is_deleted);

-- aggregator_clienttransportagency --------------------------------------------
CREATE TABLE IF NOT EXISTS public.aggregator_clienttransportagency (
	id bigserial NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL DEFAULT false,
	deleted_at timestamptz NULL,
	deleted_by_id int8 NULL,
	created_by_id int8 NULL,
	client_id int8 NOT NULL,
	transport_agency_id int8 NOT NULL,
	is_primary bool NOT NULL DEFAULT false,
	CONSTRAINT aggregator_clienttransportagency_pkey PRIMARY KEY (id),
	CONSTRAINT uniq_clienttransportagency_client_agency UNIQUE (client_id, transport_agency_id)
);
CREATE INDEX IF NOT EXISTS aggregator_clienttransportagency_client_id_idx ON public.aggregator_clienttransportagency USING btree (client_id);
CREATE INDEX IF NOT EXISTS aggregator_clienttransportagency_transport_agency_id_idx ON public.aggregator_clienttransportagency USING btree (transport_agency_id);
CREATE INDEX IF NOT EXISTS aggregator_clienttransportagency_is_deleted_idx ON public.aggregator_clienttransportagency USING btree (is_deleted);
CREATE INDEX IF NOT EXISTS aggregator_clienttransportagency_created_by_id_idx ON public.aggregator_clienttransportagency USING btree (created_by_id);
CREATE INDEX IF NOT EXISTS aggregator_clienttransportagency_deleted_by_id_idx ON public.aggregator_clienttransportagency USING btree (deleted_by_id);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_clienttransportagency_one_primary ON public.aggregator_clienttransportagency USING btree (client_id) WHERE (is_primary AND NOT is_deleted);

-- aggregator_crop -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.aggregator_crop (
	id bigserial NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL DEFAULT false,
	deleted_at timestamptz NULL,
	deleted_by_id int8 NULL,
	created_by_id int8 NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT aggregator_crop_pkey PRIMARY KEY (id),
	CONSTRAINT uniq_crop_name UNIQUE (name)
);
CREATE INDEX IF NOT EXISTS aggregator_crop_is_deleted_idx ON public.aggregator_crop USING btree (is_deleted);
CREATE INDEX IF NOT EXISTS aggregator_crop_created_by_id_idx ON public.aggregator_crop USING btree (created_by_id);
CREATE INDEX IF NOT EXISTS aggregator_crop_deleted_by_id_idx ON public.aggregator_crop USING btree (deleted_by_id);

-- aggregator_product ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.aggregator_product (
	id bigserial NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL DEFAULT false,
	deleted_at timestamptz NULL,
	deleted_by_id int8 NULL,
	created_by_id int8 NULL,
	public_id varchar(20) NOT NULL,
	"name" varchar(255) NOT NULL,
	crop_id int8 NOT NULL,
	buying_price numeric(12, 2) NOT NULL,
	selling_price numeric(12, 2) NOT NULL,
	CONSTRAINT aggregator_product_pkey PRIMARY KEY (id),
	CONSTRAINT aggregator_product_public_id_key UNIQUE (public_id),
	CONSTRAINT uniq_product_name_crop UNIQUE (name, crop_id),
	CONSTRAINT ck_product_prices_non_negative CHECK (buying_price >= 0 AND selling_price >= 0)
);
CREATE INDEX IF NOT EXISTS aggregator_product_public_id_like ON public.aggregator_product USING btree (public_id varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS aggregator_product_crop_id_idx ON public.aggregator_product USING btree (crop_id);
CREATE INDEX IF NOT EXISTS aggregator_product_is_deleted_idx ON public.aggregator_product USING btree (is_deleted);
CREATE INDEX IF NOT EXISTS aggregator_product_created_by_id_idx ON public.aggregator_product USING btree (created_by_id);
CREATE INDEX IF NOT EXISTS aggregator_product_deleted_by_id_idx ON public.aggregator_product USING btree (deleted_by_id);

-- aggregator_productpackaging -------------------------------------------------
CREATE TABLE IF NOT EXISTS public.aggregator_productpackaging (
	id bigserial NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL DEFAULT false,
	deleted_at timestamptz NULL,
	deleted_by_id int8 NULL,
	created_by_id int8 NULL,
	public_id varchar(20) NOT NULL,
	product_id int8 NOT NULL,
	packing_bag_weight numeric(8, 3) NOT NULL,
	packing_bags int8 NOT NULL,
	CONSTRAINT aggregator_productpackaging_pkey PRIMARY KEY (id),
	CONSTRAINT aggregator_productpackaging_public_id_key UNIQUE (public_id),
	CONSTRAINT uniq_productpackaging_product_weight_bags UNIQUE (product_id, packing_bag_weight, packing_bags),
	CONSTRAINT ck_productpackaging_positive CHECK (packing_bag_weight > 0 AND packing_bags > 0),
	CONSTRAINT aggregator_productpackaging_packing_bags_check CHECK (packing_bags >= 0)
);
CREATE INDEX IF NOT EXISTS aggregator_productpackaging_public_id_like ON public.aggregator_productpackaging USING btree (public_id varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS aggregator_productpackaging_product_id_idx ON public.aggregator_productpackaging USING btree (product_id);
CREATE INDEX IF NOT EXISTS aggregator_productpackaging_is_deleted_idx ON public.aggregator_productpackaging USING btree (is_deleted);
CREATE INDEX IF NOT EXISTS aggregator_productpackaging_created_by_id_idx ON public.aggregator_productpackaging USING btree (created_by_id);
CREATE INDEX IF NOT EXISTS aggregator_productpackaging_deleted_by_id_idx ON public.aggregator_productpackaging USING btree (deleted_by_id);

-- aggregator_dispatchdetails --------------------------------------------------
CREATE TABLE IF NOT EXISTS public.aggregator_dispatchdetails (
	id bigserial NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL DEFAULT false,
	deleted_at timestamptz NULL,
	deleted_by_id int8 NULL,
	client_id int8 NOT NULL,
	dispatched_by_id int8 NOT NULL,
	dispatch_date date NOT NULL,
	from_city_id int8 NOT NULL,
	to_city_id int8 NOT NULL,
	lr_number varchar(64) NOT NULL,
	CONSTRAINT aggregator_dispatchdetails_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS aggregator_dispatchdetails_client_id_idx ON public.aggregator_dispatchdetails USING btree (client_id);
CREATE INDEX IF NOT EXISTS aggregator_dispatchdetails_dispatched_by_id_idx ON public.aggregator_dispatchdetails USING btree (dispatched_by_id);
CREATE INDEX IF NOT EXISTS aggregator_dispatchdetails_from_city_id_idx ON public.aggregator_dispatchdetails USING btree (from_city_id);
CREATE INDEX IF NOT EXISTS aggregator_dispatchdetails_to_city_id_idx ON public.aggregator_dispatchdetails USING btree (to_city_id);
CREATE INDEX IF NOT EXISTS aggregator_dispatchdetails_is_deleted_idx ON public.aggregator_dispatchdetails USING btree (is_deleted);
CREATE INDEX IF NOT EXISTS aggregator_dispatchdetails_deleted_by_id_idx ON public.aggregator_dispatchdetails USING btree (deleted_by_id);

-- aggregator_privatedispatchdetails -------------------------------------------
CREATE TABLE IF NOT EXISTS public.aggregator_privatedispatchdetails (
	id bigserial NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL DEFAULT false,
	deleted_at timestamptz NULL,
	deleted_by_id int8 NULL,
	client_id int8 NOT NULL,
	dispatched_by_id int8 NOT NULL,
	dispatch_date date NOT NULL,
	from_city_id int8 NOT NULL,
	to_city_id int8 NOT NULL,
	vehicle_number varchar(32) NOT NULL,
	driver_number varchar(10) NOT NULL,
	CONSTRAINT aggregator_privatedispatchdetails_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS aggregator_privatedispatchdetails_client_id_idx ON public.aggregator_privatedispatchdetails USING btree (client_id);
CREATE INDEX IF NOT EXISTS aggregator_privatedispatchdetails_dispatched_by_id_idx ON public.aggregator_privatedispatchdetails USING btree (dispatched_by_id);
CREATE INDEX IF NOT EXISTS aggregator_privatedispatchdetails_from_city_id_idx ON public.aggregator_privatedispatchdetails USING btree (from_city_id);
CREATE INDEX IF NOT EXISTS aggregator_privatedispatchdetails_to_city_id_idx ON public.aggregator_privatedispatchdetails USING btree (to_city_id);
CREATE INDEX IF NOT EXISTS aggregator_privatedispatchdetails_is_deleted_idx ON public.aggregator_privatedispatchdetails USING btree (is_deleted);
CREATE INDEX IF NOT EXISTS aggregator_privatedispatchdetails_deleted_by_id_idx ON public.aggregator_privatedispatchdetails USING btree (deleted_by_id);

-- aggregator_order ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.aggregator_order (
	id bigserial NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL DEFAULT false,
	deleted_at timestamptz NULL,
	deleted_by_id int8 NULL,
	created_by_id int8 NULL,
	public_id varchar(20) NOT NULL,
	client_id int8 NOT NULL,
	delivery_address_id int8 NOT NULL,
	status_id int8 NOT NULL,
	expected_delivery_date date NOT NULL,
	actual_delivery_date date NULL,
	dispatch_details_id int8 NULL,
	private_dispatch_details_id int8 NULL,
	special_comments text NOT NULL,
	CONSTRAINT aggregator_order_pkey PRIMARY KEY (id),
	CONSTRAINT aggregator_order_public_id_key UNIQUE (public_id),
	CONSTRAINT ck_order_not_both_dispatch_details CHECK (NOT (dispatch_details_id IS NOT NULL AND private_dispatch_details_id IS NOT NULL))
);
CREATE INDEX IF NOT EXISTS aggregator_order_public_id_like ON public.aggregator_order USING btree (public_id varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS aggregator_order_client_id_idx ON public.aggregator_order USING btree (client_id);
CREATE INDEX IF NOT EXISTS aggregator_order_delivery_address_id_idx ON public.aggregator_order USING btree (delivery_address_id);
CREATE INDEX IF NOT EXISTS aggregator_order_status_id_idx ON public.aggregator_order USING btree (status_id);
CREATE INDEX IF NOT EXISTS aggregator_order_dispatch_details_id_idx ON public.aggregator_order USING btree (dispatch_details_id);
CREATE INDEX IF NOT EXISTS aggregator_order_private_dispatch_details_id_idx ON public.aggregator_order USING btree (private_dispatch_details_id);
CREATE INDEX IF NOT EXISTS aggregator_order_is_deleted_idx ON public.aggregator_order USING btree (is_deleted);
CREATE INDEX IF NOT EXISTS aggregator_order_created_by_id_idx ON public.aggregator_order USING btree (created_by_id);
CREATE INDEX IF NOT EXISTS aggregator_order_deleted_by_id_idx ON public.aggregator_order USING btree (deleted_by_id);

-- aggregator_orderitem --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.aggregator_orderitem (
	id bigserial NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL DEFAULT false,
	deleted_at timestamptz NULL,
	deleted_by_id int8 NULL,
	created_by_id int8 NULL,
	order_id int8 NOT NULL,
	product_packaging_id int8 NOT NULL,
	negotiated_selling_price numeric(12, 2) NOT NULL,
	quantity int8 NOT NULL,
	CONSTRAINT aggregator_orderitem_pkey PRIMARY KEY (id),
	CONSTRAINT uniq_orderitem_order_packaging UNIQUE (order_id, product_packaging_id),
	CONSTRAINT ck_orderitem_positive CHECK (negotiated_selling_price >= 0 AND quantity > 0),
	CONSTRAINT aggregator_orderitem_quantity_check CHECK (quantity >= 0)
);
CREATE INDEX IF NOT EXISTS aggregator_orderitem_order_id_idx ON public.aggregator_orderitem USING btree (order_id);
CREATE INDEX IF NOT EXISTS aggregator_orderitem_product_packaging_id_idx ON public.aggregator_orderitem USING btree (product_packaging_id);
CREATE INDEX IF NOT EXISTS aggregator_orderitem_is_deleted_idx ON public.aggregator_orderitem USING btree (is_deleted);
CREATE INDEX IF NOT EXISTS aggregator_orderitem_created_by_id_idx ON public.aggregator_orderitem USING btree (created_by_id);
CREATE INDEX IF NOT EXISTS aggregator_orderitem_deleted_by_id_idx ON public.aggregator_orderitem USING btree (deleted_by_id);

-- Foreign keys for the sales-domain tables ------------------------------------
ALTER TABLE public.aggregator_status ADD CONSTRAINT aggregator_status_created_by_id_fk FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_status ADD CONSTRAINT aggregator_status_deleted_by_id_fk FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.aggregator_transportagency ADD CONSTRAINT aggregator_transportagency_created_by_id_fk FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_transportagency ADD CONSTRAINT aggregator_transportagency_deleted_by_id_fk FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.aggregator_contact ADD CONSTRAINT aggregator_contact_created_by_id_fk FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_contact ADD CONSTRAINT aggregator_contact_deleted_by_id_fk FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.aggregator_client ADD CONSTRAINT aggregator_client_status_id_fk FOREIGN KEY (status_id) REFERENCES public.aggregator_status(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_client ADD CONSTRAINT aggregator_client_verified_by_id_fk FOREIGN KEY (verified_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_client ADD CONSTRAINT aggregator_client_created_by_id_fk FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_client ADD CONSTRAINT aggregator_client_deleted_by_id_fk FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.aggregator_clientaddress ADD CONSTRAINT aggregator_clientaddress_client_id_fk FOREIGN KEY (client_id) REFERENCES public.aggregator_client(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_clientaddress ADD CONSTRAINT aggregator_clientaddress_address_id_fk FOREIGN KEY (address_id) REFERENCES public.aggregator_address(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_clientaddress ADD CONSTRAINT aggregator_clientaddress_created_by_id_fk FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_clientaddress ADD CONSTRAINT aggregator_clientaddress_deleted_by_id_fk FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.aggregator_clientcontact ADD CONSTRAINT aggregator_clientcontact_client_id_fk FOREIGN KEY (client_id) REFERENCES public.aggregator_client(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_clientcontact ADD CONSTRAINT aggregator_clientcontact_contact_id_fk FOREIGN KEY (contact_id) REFERENCES public.aggregator_contact(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_clientcontact ADD CONSTRAINT aggregator_clientcontact_created_by_id_fk FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_clientcontact ADD CONSTRAINT aggregator_clientcontact_deleted_by_id_fk FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.aggregator_clienttransportagency ADD CONSTRAINT aggregator_clienttransportagency_client_id_fk FOREIGN KEY (client_id) REFERENCES public.aggregator_client(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_clienttransportagency ADD CONSTRAINT aggregator_clienttransportagency_agency_id_fk FOREIGN KEY (transport_agency_id) REFERENCES public.aggregator_transportagency(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_clienttransportagency ADD CONSTRAINT aggregator_clienttransportagency_created_by_id_fk FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_clienttransportagency ADD CONSTRAINT aggregator_clienttransportagency_deleted_by_id_fk FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.aggregator_crop ADD CONSTRAINT aggregator_crop_created_by_id_fk FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_crop ADD CONSTRAINT aggregator_crop_deleted_by_id_fk FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.aggregator_product ADD CONSTRAINT aggregator_product_crop_id_fk FOREIGN KEY (crop_id) REFERENCES public.aggregator_crop(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_product ADD CONSTRAINT aggregator_product_created_by_id_fk FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_product ADD CONSTRAINT aggregator_product_deleted_by_id_fk FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.aggregator_productpackaging ADD CONSTRAINT aggregator_productpackaging_product_id_fk FOREIGN KEY (product_id) REFERENCES public.aggregator_product(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_productpackaging ADD CONSTRAINT aggregator_productpackaging_created_by_id_fk FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_productpackaging ADD CONSTRAINT aggregator_productpackaging_deleted_by_id_fk FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.aggregator_dispatchdetails ADD CONSTRAINT aggregator_dispatchdetails_client_id_fk FOREIGN KEY (client_id) REFERENCES public.aggregator_client(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_dispatchdetails ADD CONSTRAINT aggregator_dispatchdetails_dispatched_by_id_fk FOREIGN KEY (dispatched_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_dispatchdetails ADD CONSTRAINT aggregator_dispatchdetails_from_city_id_fk FOREIGN KEY (from_city_id) REFERENCES public.aggregator_city(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_dispatchdetails ADD CONSTRAINT aggregator_dispatchdetails_to_city_id_fk FOREIGN KEY (to_city_id) REFERENCES public.aggregator_city(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_dispatchdetails ADD CONSTRAINT aggregator_dispatchdetails_deleted_by_id_fk FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.aggregator_privatedispatchdetails ADD CONSTRAINT aggregator_privatedispatchdetails_client_id_fk FOREIGN KEY (client_id) REFERENCES public.aggregator_client(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_privatedispatchdetails ADD CONSTRAINT aggregator_privatedispatchdetails_dispatched_by_id_fk FOREIGN KEY (dispatched_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_privatedispatchdetails ADD CONSTRAINT aggregator_privatedispatchdetails_from_city_id_fk FOREIGN KEY (from_city_id) REFERENCES public.aggregator_city(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_privatedispatchdetails ADD CONSTRAINT aggregator_privatedispatchdetails_to_city_id_fk FOREIGN KEY (to_city_id) REFERENCES public.aggregator_city(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_privatedispatchdetails ADD CONSTRAINT aggregator_privatedispatchdetails_deleted_by_id_fk FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.aggregator_order ADD CONSTRAINT aggregator_order_client_id_fk FOREIGN KEY (client_id) REFERENCES public.aggregator_client(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_order ADD CONSTRAINT aggregator_order_delivery_address_id_fk FOREIGN KEY (delivery_address_id) REFERENCES public.aggregator_address(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_order ADD CONSTRAINT aggregator_order_status_id_fk FOREIGN KEY (status_id) REFERENCES public.aggregator_status(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_order ADD CONSTRAINT aggregator_order_dispatch_details_id_fk FOREIGN KEY (dispatch_details_id) REFERENCES public.aggregator_dispatchdetails(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_order ADD CONSTRAINT aggregator_order_private_dispatch_details_id_fk FOREIGN KEY (private_dispatch_details_id) REFERENCES public.aggregator_privatedispatchdetails(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_order ADD CONSTRAINT aggregator_order_created_by_id_fk FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_order ADD CONSTRAINT aggregator_order_deleted_by_id_fk FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.aggregator_orderitem ADD CONSTRAINT aggregator_orderitem_order_id_fk FOREIGN KEY (order_id) REFERENCES public.aggregator_order(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_orderitem ADD CONSTRAINT aggregator_orderitem_product_packaging_id_fk FOREIGN KEY (product_packaging_id) REFERENCES public.aggregator_productpackaging(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_orderitem ADD CONSTRAINT aggregator_orderitem_created_by_id_fk FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_orderitem ADD CONSTRAINT aggregator_orderitem_deleted_by_id_fk FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;


-- =============================================================================
-- Django admin search performance (merged from admin_perf.sql)
-- =============================================================================
-- The two GIN indexes back the Django admin's ILIKE '%term%' search on the user
-- directory (name/email); without them those searches fall back to a full table
-- scan as the table grows. phone_number is already covered by its unique btree
-- index. The pg_trgm extension is required before the gin_trgm_ops indexes can
-- exist. Idempotent: safe to re-run.
--
-- NOTE: CREATE EXTENSION cannot run inside a transaction block in some SQL
-- tools. If yours complains, run just the next line on its own, then re-run.
--
-- Login speed: settings.PASSWORD_HASHERS prefers Argon2, which verifies ~5-10x
-- faster than the seeded PBKDF2 hashes. Existing hashes only move to Argon2 on
-- the next password set/reset, so reset the admin password once after deploying.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX IF NOT EXISTS authentication_user_name_trgm_idx
    ON public.authentication_user USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS authentication_user_email_trgm_idx
    ON public.authentication_user USING gin (email gin_trgm_ops);


-- =============================================================================
-- 24h session/token authentication support (merged from session_auth_24h.sql)
-- =============================================================================
-- Reuses the tables DRF/Django already create (authtoken_token, django_session);
-- no new table -- just the FK + expiry-sweep indexes the 24h cleanup filters on.
-- Idempotent: safe to re-run.
--
-- authtoken_token.user_id -> authentication_user.id (ON DELETE CASCADE) is
-- already declared above; django_session (expire_date) index is already created
-- above. Only the authtoken (created) sweep index is added here.
-- =============================================================================

CREATE INDEX IF NOT EXISTS authtoken_token_created_idx
    ON public.authtoken_token (created);
