CREATE TABLE public.auth_group (
	id bigserial NOT NULL,
	"name" varchar(150) NOT NULL,
	CONSTRAINT auth_group_id_not_null NOT NULL id,
	CONSTRAINT auth_group_name_key UNIQUE (name),
	CONSTRAINT auth_group_name_not_null NOT NULL name,
	CONSTRAINT auth_group_pkey PRIMARY KEY (id)
);

CREATE TABLE public.django_content_type (
	id bigserial NOT NULL,
	app_label varchar(100) NOT NULL,
	model varchar(100) NOT NULL,
	CONSTRAINT django_content_type_app_label_model_key UNIQUE (app_label, model),
	CONSTRAINT django_content_type_app_label_not_null NOT NULL app_label,
	CONSTRAINT django_content_type_id_not_null NOT NULL id,
	CONSTRAINT django_content_type_model_not_null NOT NULL model,
	CONSTRAINT django_content_type_pkey PRIMARY KEY (id)
);

CREATE TABLE public.django_migrations (
	id bigserial NOT NULL,
	app varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	applied timestamp NOT NULL,
	CONSTRAINT django_migrations_app_not_null NOT NULL app,
	CONSTRAINT django_migrations_applied_not_null NOT NULL applied,
	CONSTRAINT django_migrations_id_not_null NOT NULL id,
	CONSTRAINT django_migrations_name_not_null NOT NULL name,
	CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);
CREATE INDEX django_migrations_app_idx ON public.django_migrations USING btree (app);

CREATE TABLE public.django_session (
	session_key varchar(40) NOT NULL,
	session_data text NOT NULL,
	expire_date timestamp NOT NULL,
	CONSTRAINT django_session_expire_date_not_null NOT NULL expire_date,
	CONSTRAINT django_session_pkey PRIMARY KEY (session_key),
	CONSTRAINT django_session_session_data_not_null NOT NULL session_data,
	CONSTRAINT django_session_session_key_not_null NOT NULL session_key
);
CREATE INDEX django_session_expire_date_idx ON public.django_session USING btree (expire_date);

CREATE TABLE public.auth_permission (
	id bigserial NOT NULL,
	"name" varchar(255) NOT NULL,
	content_type_id int8 NOT NULL,
	codename varchar(100) NOT NULL,
	CONSTRAINT auth_permission_codename_not_null NOT NULL codename,
	CONSTRAINT auth_permission_content_type_id_codename_key UNIQUE (content_type_id, codename),
	CONSTRAINT auth_permission_content_type_id_not_null NOT NULL content_type_id,
	CONSTRAINT auth_permission_id_not_null NOT NULL id,
	CONSTRAINT auth_permission_name_not_null NOT NULL name,
	CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
	CONSTRAINT auth_permission_content_type_id_fkey FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id)
);
CREATE INDEX auth_permission_content_type_id_idx ON public.auth_permission USING btree (content_type_id);

CREATE TABLE public.authentication_user (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"password" varchar(128) NOT NULL,
	last_login timestamptz NULL,
	is_superuser bool NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	phone_number varchar(10) NOT NULL,
	"name" varchar(255) NOT NULL,
	email varchar(254) NULL,
	totp_secret varchar(32) NULL,
	totp_enabled bool NOT NULL,
	totp_last_counter int8 NULL,
	failed_totp_attempts int4 NOT NULL DEFAULT 0,
	totp_lockout_until timestamptz NULL,
	is_verified bool NOT NULL,
	is_staff bool NOT NULL,
	is_active bool NOT NULL,
	date_joined timestamptz NOT NULL,
	created_by_id int8 NULL,
	verified_by_id int8 NULL,
	CONSTRAINT authentication_user_created_at_not_null NOT NULL created_at,
	CONSTRAINT authentication_user_date_joined_not_null NOT NULL date_joined,
	CONSTRAINT authentication_user_id_not_null NOT NULL id,
	CONSTRAINT authentication_user_is_active_not_null NOT NULL is_active,
	CONSTRAINT authentication_user_is_staff_not_null NOT NULL is_staff,
	CONSTRAINT authentication_user_is_superuser_not_null NOT NULL is_superuser,
	CONSTRAINT authentication_user_is_verified_not_null NOT NULL is_verified,
	CONSTRAINT authentication_user_name_not_null NOT NULL name,
	CONSTRAINT authentication_user_password_not_null NOT NULL password,
	CONSTRAINT authentication_user_phone_number_key UNIQUE (phone_number),
	CONSTRAINT authentication_user_phone_number_not_null NOT NULL phone_number,
	CONSTRAINT authentication_user_pkey PRIMARY KEY (id),
	CONSTRAINT authentication_user_totp_enabled_not_null NOT NULL totp_enabled,
	CONSTRAINT authentication_user_failed_totp_attempts_not_null NOT NULL failed_totp_attempts,
	CONSTRAINT authentication_user_updated_at_not_null NOT NULL updated_at,
	CONSTRAINT authentication_user_created_by_id_d3f2a616_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT authentication_user_verified_by_id_e9e11f40_fk_authentic FOREIGN KEY (verified_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX authentication_user_created_by_id_d3f2a616 ON public.authentication_user USING btree (created_by_id);
CREATE INDEX authentication_user_phone_number_f8159965_like ON public.authentication_user USING btree (phone_number varchar_pattern_ops);
CREATE INDEX authentication_user_verified_by_id_e9e11f40 ON public.authentication_user USING btree (verified_by_id);

CREATE TABLE public.authentication_user_groups (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NOT NULL,
	group_id int4 NOT NULL,
	CONSTRAINT authentication_user_groups_group_id_not_null NOT NULL group_id,
	CONSTRAINT authentication_user_groups_id_not_null NOT NULL id,
	CONSTRAINT authentication_user_groups_pkey PRIMARY KEY (id),
	CONSTRAINT authentication_user_groups_user_id_group_id_8af031ac_uniq UNIQUE (user_id, group_id),
	CONSTRAINT authentication_user_groups_user_id_not_null NOT NULL user_id,
	CONSTRAINT authentication_user__user_id_30868577_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT authentication_user_groups_group_id_6b5c44b7_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX authentication_user_groups_group_id_6b5c44b7 ON public.authentication_user_groups USING btree (group_id);
CREATE INDEX authentication_user_groups_user_id_30868577 ON public.authentication_user_groups USING btree (user_id);

CREATE TABLE public.authentication_user_user_permissions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NOT NULL,
	permission_id int4 NOT NULL,
	CONSTRAINT authentication_user_user_permissions_id_not_null NOT NULL id,
	CONSTRAINT authentication_user_user_permissions_permission_id_not_null NOT NULL permission_id,
	CONSTRAINT authentication_user_user_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT authentication_user_user_permissions_user_id_not_null NOT NULL user_id,
	CONSTRAINT authentication_user_user_user_id_permission_id_ec51b09f_uniq UNIQUE (user_id, permission_id),
	CONSTRAINT authentication_user__permission_id_ea6be19a_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT authentication_user__user_id_736ebf7e_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX authentication_user_user_permissions_permission_id_ea6be19a ON public.authentication_user_user_permissions USING btree (permission_id);
CREATE INDEX authentication_user_user_permissions_user_id_736ebf7e ON public.authentication_user_user_permissions USING btree (user_id);


CREATE TABLE public.django_admin_log (
	id bigserial NOT NULL,
	action_time timestamp NOT NULL,
	user_id int8 NULL,
	content_type_id int8 NULL,
	object_id text NULL,
	object_repr varchar(200) NOT NULL,
	action_flag int2 NOT NULL,
	change_message text NOT NULL,
	CONSTRAINT django_admin_log_action_flag_not_null NOT NULL action_flag,
	CONSTRAINT django_admin_log_action_time_not_null NOT NULL action_time,
	CONSTRAINT django_admin_log_change_message_not_null NOT NULL change_message,
	CONSTRAINT django_admin_log_id_not_null NOT NULL id,
	CONSTRAINT django_admin_log_object_repr_not_null NOT NULL object_repr,
	CONSTRAINT django_admin_log_pkey PRIMARY KEY (id),
	CONSTRAINT django_admin_log_content_type_id_fkey FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id),
	CONSTRAINT django_admin_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL
);
CREATE INDEX django_admin_log_content_type_id_idx ON public.django_admin_log USING btree (content_type_id);
CREATE INDEX django_admin_log_user_id_idx ON public.django_admin_log USING btree (user_id);


CREATE TABLE public.auth_group_permissions (
	id bigserial NOT NULL,
	group_id int8 NOT NULL,
	permission_id int8 NOT NULL,
	CONSTRAINT auth_group_permissions_group_id_not_null NOT NULL group_id,
	CONSTRAINT auth_group_permissions_group_id_permission_id_key UNIQUE (group_id, permission_id),
	CONSTRAINT auth_group_permissions_id_not_null NOT NULL id,
	CONSTRAINT auth_group_permissions_permission_id_not_null NOT NULL permission_id,
	CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT auth_group_permissions_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.auth_group(id) ON DELETE CASCADE,
	CONSTRAINT auth_group_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) ON DELETE CASCADE
);
CREATE INDEX auth_group_permissions_group_id_idx ON public.auth_group_permissions USING btree (group_id);
CREATE INDEX auth_group_permissions_permission_id_idx ON public.auth_group_permissions USING btree (permission_id);

CREATE TABLE public.authentication_admin (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL,
	deleted_at timestamptz NULL,
	deleted_by_id int8 NULL,
	created_by_id int8 NULL,
	user_id int8 NOT NULL,
	CONSTRAINT authentication_admin_created_at_not_null NOT NULL created_at,
	CONSTRAINT authentication_admin_id_not_null NOT NULL id,
	CONSTRAINT authentication_admin_is_deleted_not_null NOT NULL is_deleted,
	CONSTRAINT authentication_admin_pkey PRIMARY KEY (id),
	CONSTRAINT authentication_admin_updated_at_not_null NOT NULL updated_at,
	CONSTRAINT authentication_admin_user_id_key UNIQUE (user_id),
	CONSTRAINT authentication_admin_user_id_not_null NOT NULL user_id,
	CONSTRAINT authentication_admin_created_by_id_16c58a5c_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT authentication_admin_deleted_by_id_ba1bf8d2_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT authentication_admin_user_id_2e7e3e20_fk_authentication_user_id FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX authentication_admin_created_by_id_16c58a5c ON public.authentication_admin USING btree (created_by_id);
CREATE INDEX authentication_admin_deleted_by_id_ba1bf8d2 ON public.authentication_admin USING btree (deleted_by_id);
CREATE INDEX authentication_admin_is_deleted_699f106c ON public.authentication_admin USING btree (is_deleted);

CREATE TABLE public.authentication_salesperson (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL,
	deleted_at timestamptz NULL,
	deleted_by_id int8 NULL,
	created_by_id int8 NULL,
	user_id int8 NOT NULL,
	CONSTRAINT authentication_salesperson_created_at_not_null NOT NULL created_at,
	CONSTRAINT authentication_salesperson_id_not_null NOT NULL id,
	CONSTRAINT authentication_salesperson_is_deleted_not_null NOT NULL is_deleted,
	CONSTRAINT authentication_salesperson_pkey PRIMARY KEY (id),
	CONSTRAINT authentication_salesperson_updated_at_not_null NOT NULL updated_at,
	CONSTRAINT authentication_salesperson_user_id_key UNIQUE (user_id),
	CONSTRAINT authentication_salesperson_user_id_not_null NOT NULL user_id,
	CONSTRAINT authentication_sales_created_by_id_a1b95e80_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT authentication_sales_deleted_by_id_a5490b20_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT authentication_sales_user_id_23cc5271_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX authentication_salesperson_created_by_id_a1b95e80 ON public.authentication_salesperson USING btree (created_by_id);
CREATE INDEX authentication_salesperson_deleted_by_id_a5490b20 ON public.authentication_salesperson USING btree (deleted_by_id);
CREATE INDEX authentication_salesperson_is_deleted_e9d86904 ON public.authentication_salesperson USING btree (is_deleted);

CREATE TABLE public.authtoken_token (
	"key" varchar(40) NOT NULL,
	created timestamptz NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT authtoken_token_created_not_null NOT NULL created,
	CONSTRAINT authtoken_token_key_not_null NOT NULL key,
	CONSTRAINT authtoken_token_pkey PRIMARY KEY (key),
	CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id),
	CONSTRAINT authtoken_token_user_id_not_null NOT NULL user_id
);
CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);

CREATE TABLE public.aggregator_address (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL,
	deleted_at timestamptz NULL,
	address_line_1 varchar(255) NOT NULL,
	address_line_2 varchar(255) NOT NULL,
	created_by_id int8 NULL,
	deleted_by_id int8 NULL,
	city_id int8 NOT NULL,
	country_id int8 NOT NULL,
	pincode_id int8 NOT NULL,
	state_id int8 NOT NULL,
	CONSTRAINT aggregator_address_address_line_1_not_null NOT NULL address_line_1,
	CONSTRAINT aggregator_address_address_line_2_not_null NOT NULL address_line_2,
	CONSTRAINT aggregator_address_city_id_not_null NOT NULL city_id,
	CONSTRAINT aggregator_address_country_id_not_null NOT NULL country_id,
	CONSTRAINT aggregator_address_created_at_not_null NOT NULL created_at,
	CONSTRAINT aggregator_address_id_not_null NOT NULL id,
	CONSTRAINT aggregator_address_is_deleted_not_null NOT NULL is_deleted,
	CONSTRAINT aggregator_address_pincode_id_not_null NOT NULL pincode_id,
	CONSTRAINT aggregator_address_pkey PRIMARY KEY (id),
	CONSTRAINT aggregator_address_state_id_not_null NOT NULL state_id,
	CONSTRAINT aggregator_address_updated_at_not_null NOT NULL updated_at
);
CREATE INDEX aggregator_address_city_id_96970770 ON public.aggregator_address USING btree (city_id);
CREATE INDEX aggregator_address_country_id_2f36b787 ON public.aggregator_address USING btree (country_id);
CREATE INDEX aggregator_address_created_by_id_58fd480f ON public.aggregator_address USING btree (created_by_id);
CREATE INDEX aggregator_address_deleted_by_id_dc377b3e ON public.aggregator_address USING btree (deleted_by_id);
CREATE INDEX aggregator_address_is_deleted_4785bd2d ON public.aggregator_address USING btree (is_deleted);
CREATE INDEX aggregator_address_pincode_id_08ed1fa7 ON public.aggregator_address USING btree (pincode_id);
CREATE INDEX aggregator_address_state_id_f6223e91 ON public.aggregator_address USING btree (state_id);

CREATE TABLE public.aggregator_city (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL,
	deleted_at timestamptz NULL,
	"name" varchar(255) NOT NULL,
	created_by_id int8 NULL,
	deleted_by_id int8 NULL,
	state_id int8 NOT NULL,
	CONSTRAINT aggregator_city_created_at_not_null NOT NULL created_at,
	CONSTRAINT aggregator_city_id_not_null NOT NULL id,
	CONSTRAINT aggregator_city_is_deleted_not_null NOT NULL is_deleted,
	CONSTRAINT aggregator_city_name_not_null NOT NULL name,
	CONSTRAINT aggregator_city_pkey PRIMARY KEY (id),
	CONSTRAINT aggregator_city_state_id_not_null NOT NULL state_id,
	CONSTRAINT aggregator_city_updated_at_not_null NOT NULL updated_at,
	CONSTRAINT uniq_city_state_name UNIQUE (state_id, name)
);
CREATE INDEX aggregator_city_created_by_id_fefe63ee ON public.aggregator_city USING btree (created_by_id);
CREATE INDEX aggregator_city_deleted_by_id_73898851 ON public.aggregator_city USING btree (deleted_by_id);
CREATE INDEX aggregator_city_is_deleted_5d1d102e ON public.aggregator_city USING btree (is_deleted);
CREATE INDEX aggregator_city_state_id_cf1a9769 ON public.aggregator_city USING btree (state_id);

CREATE TABLE public.aggregator_country (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL,
	deleted_at timestamptz NULL,
	"name" varchar(255) NOT NULL,
	iso_code varchar(3) NOT NULL,
	created_by_id int8 NULL,
	deleted_by_id int8 NULL,
	CONSTRAINT aggregator_country_created_at_not_null NOT NULL created_at,
	CONSTRAINT aggregator_country_id_not_null NOT NULL id,
	CONSTRAINT aggregator_country_is_deleted_not_null NOT NULL is_deleted,
	CONSTRAINT aggregator_country_iso_code_key UNIQUE (iso_code),
	CONSTRAINT aggregator_country_iso_code_not_null NOT NULL iso_code,
	CONSTRAINT aggregator_country_name_key UNIQUE (name),
	CONSTRAINT aggregator_country_name_not_null NOT NULL name,
	CONSTRAINT aggregator_country_pkey PRIMARY KEY (id),
	CONSTRAINT aggregator_country_updated_at_not_null NOT NULL updated_at
);
CREATE INDEX aggregator_country_created_by_id_793f2516 ON public.aggregator_country USING btree (created_by_id);
CREATE INDEX aggregator_country_deleted_by_id_92252d30 ON public.aggregator_country USING btree (deleted_by_id);
CREATE INDEX aggregator_country_is_deleted_c078494b ON public.aggregator_country USING btree (is_deleted);
CREATE INDEX aggregator_country_iso_code_65034c84_like ON public.aggregator_country USING btree (iso_code varchar_pattern_ops);
CREATE INDEX aggregator_country_name_74cb7636_like ON public.aggregator_country USING btree (name varchar_pattern_ops);

CREATE TABLE public.aggregator_pincode (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL,
	deleted_at timestamptz NULL,
	code varchar(10) NOT NULL,
	city_id int8 NOT NULL,
	created_by_id int8 NULL,
	deleted_by_id int8 NULL,
	CONSTRAINT aggregator_pincode_city_id_not_null NOT NULL city_id,
	CONSTRAINT aggregator_pincode_code_not_null NOT NULL code,
	CONSTRAINT aggregator_pincode_created_at_not_null NOT NULL created_at,
	CONSTRAINT aggregator_pincode_id_not_null NOT NULL id,
	CONSTRAINT aggregator_pincode_is_deleted_not_null NOT NULL is_deleted,
	CONSTRAINT aggregator_pincode_pkey PRIMARY KEY (id),
	CONSTRAINT aggregator_pincode_updated_at_not_null NOT NULL updated_at,
	CONSTRAINT uniq_pincode_city_code UNIQUE (city_id, code)
);
CREATE INDEX aggregator_pincode_city_id_22cea78d ON public.aggregator_pincode USING btree (city_id);
CREATE INDEX aggregator_pincode_code_811fb568 ON public.aggregator_pincode USING btree (code);
CREATE INDEX aggregator_pincode_code_811fb568_like ON public.aggregator_pincode USING btree (code varchar_pattern_ops);
CREATE INDEX aggregator_pincode_created_by_id_27d8c46d ON public.aggregator_pincode USING btree (created_by_id);
CREATE INDEX aggregator_pincode_deleted_by_id_ce50a668 ON public.aggregator_pincode USING btree (deleted_by_id);
CREATE INDEX aggregator_pincode_is_deleted_a155fcbe ON public.aggregator_pincode USING btree (is_deleted);

CREATE TABLE public.aggregator_state (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_deleted bool NOT NULL,
	deleted_at timestamptz NULL,
	"name" varchar(255) NOT NULL,
	code varchar(10) NULL,
	country_id int8 NOT NULL,
	created_by_id int8 NULL,
	deleted_by_id int8 NULL,
	CONSTRAINT aggregator_state_country_id_not_null NOT NULL country_id,
	CONSTRAINT aggregator_state_created_at_not_null NOT NULL created_at,
	CONSTRAINT aggregator_state_id_not_null NOT NULL id,
	CONSTRAINT aggregator_state_is_deleted_not_null NOT NULL is_deleted,
	CONSTRAINT aggregator_state_name_not_null NOT NULL name,
	CONSTRAINT aggregator_state_pkey PRIMARY KEY (id),
	CONSTRAINT aggregator_state_updated_at_not_null NOT NULL updated_at,
	CONSTRAINT uniq_state_country_name UNIQUE (country_id, name)
);
CREATE INDEX aggregator_state_country_id_85c7cf77 ON public.aggregator_state USING btree (country_id);
CREATE INDEX aggregator_state_created_by_id_dfbd65c0 ON public.aggregator_state USING btree (created_by_id);
CREATE INDEX aggregator_state_deleted_by_id_13e63a1b ON public.aggregator_state USING btree (deleted_by_id);
CREATE INDEX aggregator_state_is_deleted_e8f057d4 ON public.aggregator_state USING btree (is_deleted);
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_city_id_96970770_fk_aggregator_city_id FOREIGN KEY (city_id) REFERENCES public.aggregator_city(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_country_id_2f36b787_fk_aggregator_country_id FOREIGN KEY (country_id) REFERENCES public.aggregator_country(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_created_by_id_58fd480f_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_deleted_by_id_dc377b3e_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_pincode_id_08ed1fa7_fk_aggregator_pincode_id FOREIGN KEY (pincode_id) REFERENCES public.aggregator_pincode(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_state_id_f6223e91_fk_aggregator_state_id FOREIGN KEY (state_id) REFERENCES public.aggregator_state(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_city ADD CONSTRAINT aggregator_city_created_by_id_fefe63ee_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_city ADD CONSTRAINT aggregator_city_deleted_by_id_73898851_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_city ADD CONSTRAINT aggregator_city_state_id_cf1a9769_fk_aggregator_state_id FOREIGN KEY (state_id) REFERENCES public.aggregator_state(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_country ADD CONSTRAINT aggregator_country_created_by_id_793f2516_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_country ADD CONSTRAINT aggregator_country_deleted_by_id_92252d30_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_pincode ADD CONSTRAINT aggregator_pincode_city_id_22cea78d_fk_aggregator_city_id FOREIGN KEY (city_id) REFERENCES public.aggregator_city(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_pincode ADD CONSTRAINT aggregator_pincode_created_by_id_27d8c46d_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_pincode ADD CONSTRAINT aggregator_pincode_deleted_by_id_ce50a668_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_state ADD CONSTRAINT aggregator_state_country_id_85c7cf77_fk_aggregator_country_id FOREIGN KEY (country_id) REFERENCES public.aggregator_country(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_state ADD CONSTRAINT aggregator_state_created_by_id_dfbd65c0_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_state ADD CONSTRAINT aggregator_state_deleted_by_id_13e63a1b_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;

-- ---------------------------------------------------------------------------
-- Referential actions (ON DELETE) aligned with the Django models' on_delete.
-- Postgres cannot alter a constraint's action, so each FK is dropped and
-- re-created with the matching clause. PROTECT is written as RESTRICT
-- (Postgres rejects the PROTECT keyword; they are synonyms).
-- ---------------------------------------------------------------------------

-- Django Permission: content_type -> CASCADE
ALTER TABLE public.auth_permission DROP CONSTRAINT auth_permission_content_type_id_fkey;
ALTER TABLE public.auth_permission ADD CONSTRAINT auth_permission_content_type_id_fkey FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

-- Django LogEntry: user -> CASCADE, content_type -> SET NULL
ALTER TABLE public.django_admin_log DROP CONSTRAINT django_admin_log_user_id_fkey;
ALTER TABLE public.django_admin_log ADD CONSTRAINT django_admin_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.django_admin_log DROP CONSTRAINT django_admin_log_content_type_id_fkey;
ALTER TABLE public.django_admin_log ADD CONSTRAINT django_admin_log_content_type_id_fkey FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

-- authentication_user.created_by / verified_by -> RESTRICT (PROTECT): a user
-- who created/verified others can never be deleted while referenced.
ALTER TABLE public.authentication_user DROP CONSTRAINT authentication_user_created_by_id_d3f2a616_fk_authentic;
ALTER TABLE public.authentication_user ADD CONSTRAINT authentication_user_created_by_id_d3f2a616_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.authentication_user DROP CONSTRAINT authentication_user_verified_by_id_e9e11f40_fk_authentic;
ALTER TABLE public.authentication_user ADD CONSTRAINT authentication_user_verified_by_id_e9e11f40_fk_authentic FOREIGN KEY (verified_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

-- Django M2M through tables: -> CASCADE both directions
ALTER TABLE public.authentication_user_groups DROP CONSTRAINT authentication_user__user_id_30868577_fk_authentic;
ALTER TABLE public.authentication_user_groups ADD CONSTRAINT authentication_user__user_id_30868577_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.authentication_user_groups DROP CONSTRAINT authentication_user_groups_group_id_6b5c44b7_fk_auth_group_id;
ALTER TABLE public.authentication_user_groups ADD CONSTRAINT authentication_user_groups_group_id_6b5c44b7_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.authentication_user_user_permissions DROP CONSTRAINT authentication_user__permission_id_ea6be19a_fk_auth_perm;
ALTER TABLE public.authentication_user_user_permissions ADD CONSTRAINT authentication_user__permission_id_ea6be19a_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.authentication_user_user_permissions DROP CONSTRAINT authentication_user__user_id_736ebf7e_fk_authentic;
ALTER TABLE public.authentication_user_user_permissions ADD CONSTRAINT authentication_user__user_id_736ebf7e_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

-- authentication_admin: user CASCADE, created_by RESTRICT, deleted_by SET NULL
ALTER TABLE public.authentication_admin DROP CONSTRAINT authentication_admin_user_id_2e7e3e20_fk_authentication_user_id;
ALTER TABLE public.authentication_admin ADD CONSTRAINT authentication_admin_user_id_2e7e3e20_fk_authentication_user_id FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.authentication_admin DROP CONSTRAINT authentication_admin_created_by_id_16c58a5c_fk_authentic;
ALTER TABLE public.authentication_admin ADD CONSTRAINT authentication_admin_created_by_id_16c58a5c_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.authentication_admin DROP CONSTRAINT authentication_admin_deleted_by_id_ba1bf8d2_fk_authentic;
ALTER TABLE public.authentication_admin ADD CONSTRAINT authentication_admin_deleted_by_id_ba1bf8d2_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

-- authentication_salesperson: user CASCADE, created_by RESTRICT, deleted_by SET NULL
ALTER TABLE public.authentication_salesperson DROP CONSTRAINT authentication_sales_user_id_23cc5271_fk_authentic;
ALTER TABLE public.authentication_salesperson ADD CONSTRAINT authentication_sales_user_id_23cc5271_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.authentication_salesperson DROP CONSTRAINT authentication_sales_created_by_id_a1b95e80_fk_authentic;
ALTER TABLE public.authentication_salesperson ADD CONSTRAINT authentication_sales_created_by_id_a1b95e80_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.authentication_salesperson DROP CONSTRAINT authentication_sales_deleted_by_id_a5490b20_fk_authentic;
ALTER TABLE public.authentication_salesperson ADD CONSTRAINT authentication_sales_deleted_by_id_a5490b20_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

-- aggregator geography hierarchy: RESTRICT
ALTER TABLE public.aggregator_state DROP CONSTRAINT aggregator_state_country_id_85c7cf77_fk_aggregator_country_id;
ALTER TABLE public.aggregator_state ADD CONSTRAINT aggregator_state_country_id_85c7cf77_fk_aggregator_country_id FOREIGN KEY (country_id) REFERENCES public.aggregator_country(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_city DROP CONSTRAINT aggregator_city_state_id_cf1a9769_fk_aggregator_state_id;
ALTER TABLE public.aggregator_city ADD CONSTRAINT aggregator_city_state_id_cf1a9769_fk_aggregator_state_id FOREIGN KEY (state_id) REFERENCES public.aggregator_state(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_pincode DROP CONSTRAINT aggregator_pincode_city_id_22cea78d_fk_aggregator_city_id;
ALTER TABLE public.aggregator_pincode ADD CONSTRAINT aggregator_pincode_city_id_22cea78d_fk_aggregator_city_id FOREIGN KEY (city_id) REFERENCES public.aggregator_city(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address DROP CONSTRAINT aggregator_address_pincode_id_08ed1fa7_fk_aggregator_pincode_id;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_pincode_id_08ed1fa7_fk_aggregator_pincode_id FOREIGN KEY (pincode_id) REFERENCES public.aggregator_pincode(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address DROP CONSTRAINT aggregator_address_city_id_96970770_fk_aggregator_city_id;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_city_id_96970770_fk_aggregator_city_id FOREIGN KEY (city_id) REFERENCES public.aggregator_city(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address DROP CONSTRAINT aggregator_address_state_id_f6223e91_fk_aggregator_state_id;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_state_id_f6223e91_fk_aggregator_state_id FOREIGN KEY (state_id) REFERENCES public.aggregator_state(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address DROP CONSTRAINT aggregator_address_country_id_2f36b787_fk_aggregator_country_id;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_country_id_2f36b787_fk_aggregator_country_id FOREIGN KEY (country_id) REFERENCES public.aggregator_country(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

-- aggregator audit columns: created_by RESTRICT, deleted_by SET NULL
ALTER TABLE public.aggregator_country DROP CONSTRAINT aggregator_country_created_by_id_793f2516_fk_authentic;
ALTER TABLE public.aggregator_country ADD CONSTRAINT aggregator_country_created_by_id_793f2516_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_country DROP CONSTRAINT aggregator_country_deleted_by_id_92252d30_fk_authentic;
ALTER TABLE public.aggregator_country ADD CONSTRAINT aggregator_country_deleted_by_id_92252d30_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_state DROP CONSTRAINT aggregator_state_created_by_id_dfbd65c0_fk_authentic;
ALTER TABLE public.aggregator_state ADD CONSTRAINT aggregator_state_created_by_id_dfbd65c0_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_state DROP CONSTRAINT aggregator_state_deleted_by_id_13e63a1b_fk_authentic;
ALTER TABLE public.aggregator_state ADD CONSTRAINT aggregator_state_deleted_by_id_13e63a1b_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_city DROP CONSTRAINT aggregator_city_created_by_id_fefe63ee_fk_authentic;
ALTER TABLE public.aggregator_city ADD CONSTRAINT aggregator_city_created_by_id_fefe63ee_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_city DROP CONSTRAINT aggregator_city_deleted_by_id_73898851_fk_authentic;
ALTER TABLE public.aggregator_city ADD CONSTRAINT aggregator_city_deleted_by_id_73898851_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_pincode DROP CONSTRAINT aggregator_pincode_created_by_id_27d8c46d_fk_authentic;
ALTER TABLE public.aggregator_pincode ADD CONSTRAINT aggregator_pincode_created_by_id_27d8c46d_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_pincode DROP CONSTRAINT aggregator_pincode_deleted_by_id_ce50a668_fk_authentic;
ALTER TABLE public.aggregator_pincode ADD CONSTRAINT aggregator_pincode_deleted_by_id_ce50a668_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address DROP CONSTRAINT aggregator_address_created_by_id_58fd480f_fk_authentic;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_created_by_id_58fd480f_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_user(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.aggregator_address DROP CONSTRAINT aggregator_address_deleted_by_id_dc377b3e_fk_authentic;
ALTER TABLE public.aggregator_address ADD CONSTRAINT aggregator_address_deleted_by_id_dc377b3e_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.authtoken_token ADD CONSTRAINT authtoken_token_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE authentication_salesperson
    ADD COLUMN city_id BIGINT NOT NULL,
    ADD CONSTRAINT fk_salesperson_city
        FOREIGN KEY (city_id)
        REFERENCES aggregator_city (id)
        ON DELETE RESTRICT;

CREATE INDEX authentication_salesperson_city_id
    ON authentication_salesperson (city_id);


ALTER TABLE authentication_admin
    ADD COLUMN can_update_stock_count boolean NOT NULL DEFAULT false;


